language: node_js
node_js:
- 10
cache:
  directories:
  - node_modules
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- sudo apt-get update > /dev/null
- mkdir -p ~/.ssh
- eval `ssh-agent -s`
- ssh-add -D
- echo -e "Host github.com\n  User my-machine-user\n  IdentityFile ${TRAVIS_BUILD_DIR}/ci/ssh/insecure-key\n"
  >> ~/.ssh/config
- chmod 600 ${TRAVIS_BUILD_DIR}/ci/ssh/*
- cp ${TRAVIS_BUILD_DIR}/ci/ssh/known_hosts ~/.ssh/known_hosts
- git submodule update --init --recursive
install:
- yarn install
script:
- yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: public
  target-branch: master
  on:
    branch: deployTest
