  
language: node_js
node_js:
  - 10
cache:
  directories:
  - node_modules
install:
  - yarn install
script:
  - yarn build
git:
  submodules: false
before_install:
  - sudo chown -R travis ./privRepoPush.sh
  - sudo chmod +x ./privRepoPush.sh
  - ./privRepoPush.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the travis settings page of your repository, as a secure variable
  keep-history: true
  local-dir: public
  target-branch: master
  on:
    branch: deployTest