baseurl         = "https://jayswansonce.github.io/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Jay Swanson"
  subtitle    = "grippin' and rippin'"

  cover       = "img/blog-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "faketryghost"
  fbName = "fakeghost"
  githubName = "JaySwansonCE"

  logo = ""
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "JS"
  authorAvatar = "img/jayclimb.jpg"
  authorLocation = "Logan, UT"
  authorWebsite = "https://jayswansonce.github.io/"
  authorDescription = "Climber, Engineer, Developer, Mycologist, Photographer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Main"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Projects"
  url = "/tags/project/"
  weight = 100

[[menu.main]]
  name = "About Me"
  url = "/categories/aboutMe/"
  weight = 99

[[menu.main]]
  name = "Google"
  url = "https://google.com/"
  weight = 95